# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

handlers:
  - url: /.*
    script: this field is required, but ignored
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
